# Generated by Django 3.2.9 on 2021-11-20 18:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('phone', models.CharField(max_length=10, unique=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
